### PR TITLE
Moved CreateNewMonitor to its own directory as it is a page unto itself

### PR DESCRIPTION
**Pull request by ajhollid**
Create New Monitor button now redirects to `/monitors/create` and displays the `CreateNewMonitor` page

TODO:

`CreateNewMonitor` page uses the styles from the `Monitors page`.  I simply copied the whole index.css file to the new `CreateNewMonitor` directory, so there are probably unused styles in that file.  We should remove any unused styles.

### CODE REVIEW

**Review by danielcj2 — COMMENTED** [review]
Looks good. Maybe have @MuhammadKhalilzadeh look into it since he's familiar with the code?

**Review by Skorpios604 — APPROVED** [review]
Looks great! Functional but not responsive. If you drop down to mobile size the text goes into each other. I suppose that will be fixed when the styling is fixed.

**Comment by ajhollid** [comment]
> Looks great! Functional but not responsive. If you drop down to mobile size the text goes into each other. I suppose that will be fixed when the styling is fixed.

Good call, responsiveness is something we need to address in the future, I think there are many components and pages that aren't responsive yet.

**Review by MuhammadKhalilzadeh — APPROVED** [review]
Nice code you've wrote. Looks good to me, Kudos.

**Pull request merged**
