### PR TITLE
Breadcrumbs component

### PR DESCRIPTION
**Pull request by danielcj2**
- [x] Implemented breadcrumbs component

### CODE REVIEW

**Review by alvarotorrestx — APPROVED** [review]
Looks great, nice design! 👌

**Review by ajhollid — COMMENTED** [review]
Everything looks good, but should the details page implement the same style breadcrumb?

Screenshot from 2024-08-17 11-07-36
Screenshot from 2024-08-17 11-07-40

It's kind of jarring to see the arrows change direction and the button style change :thinking:

**Comment by ajhollid** [comment]
If this PR is just to get the component merged in and implementation is coming for the rest of the pages then disregard above :joy:

**Comment by danielcj2** [comment]
> Everything looks good, but should the details page implement the same style breadcrumb?

Yes, I plan to replace all back buttons with breadcrumbs. This PR is just the initial component design to get everyone's take on it.

**Comment by gorkem-bwl** [comment]
Looks good boss!

**Pull request merged**
