### PR TITLE
Feat/issue 225 maintenance page

### PR DESCRIPTION
**Pull request by terryjung0244**
- Setup maintenance page route and menu button, moved content, updated path map - 

1. Added route setup for the maintenance page in App.jsx.
2. Added a dashboard menu button for the maintenance page in DashboardMenu.
3. Moved content with CSS from the Incidents page to the Maintenance page.
4. Updated path map in PathMap.js to include the "maintenance" route.

Thank you.

### CODE REVIEW

**Review by ajhollid — APPROVED** [review]
Everything looks OK for the most part to me.

The Incident page was overwritten though, so I had to reset it to the original version in the repository.

Please be careful about what files you make changes to and pay close attention when making pull requests.  If there is a merge conflict please reach out to the person who's code you are in conflict with :+1: 

I'll leave the specifics of the front end review to the front end devs!

**Comment by terryjung0244** [comment]
Thanks for the comments.

**Review by danielcj2 — APPROVED** [review]
Overall it looks good! It seems like we both overlooked the font size of the `button`. It should be `13px` instead. However it is a trivial change and I wouldn't be opposed to just having you sneakily adding the fix on your next PR.

**Comment by danielcj2** [comment]
> Thank you for the comments. I'll be more careful next time. There are no conflicts with the base branch. Should I proceed with merging the pull request?

Alex usually handles the merging of PRs so you don't got to worry about it! I'm assuming he's waiting for more reviews from the frontend people before he does it.

**Comment by terryjung0244** [comment]
The font size has been updated. Thank you for all the comments!

**Pull request merged**
