### PR TITLE
Add Server endpoints to ToC in README

### PR DESCRIPTION
**Pull request by alvarotorrestx**
I went ahead and linked server endpoints in the README in the layout that was shown in issue #62 

Let me know if this would suffice or should we make further updates?

### CODE REVIEW

**Comment by alvarotorrestx** [comment]
Maybe add the front end routes? Or that can probably wait until further is completed with server

**Review by popnfresh234 — APPROVED** [review]
Fantastic, thanks for taking care of this, it's a small task but it's a load off my shoulders!

Documentation can be boring but it really makes a project stand out.  Thanks your for help!

**Comment by popnfresh234** [comment]
> Maybe add the front end routes? Or that can probably wait until further is completed with server

Good point, but I don't think we've settled on routes for the front end yet, so it might be a bit premature to get documentation going there.

We'll open another issue when the time is right!

**Comment by popnfresh234** [comment]
PS  If you add something like "resolves #62" Github will automatically close that issuse when the pull request is accepted :+1:

**Comment by alvarotorrestx** [comment]
For sure, happy to start off with some sort of contribution! As things progress and I learn more about your project I'd love to see where else I can contribute too! 

I appreciate the tips also, I'll know that for future PRs 👌

**Pull request merged**
