### PR TITLE
Feat/#293 maintenance window options

### PR DESCRIPTION
**Pull request by terryjung0244**
1. feat: Add route for creating new maintenance window
- Added route `/maintenance/createnewmaintenance` to render the 
  `CreateNewMaintenance` component.  
- Wrapped `CreateNewMaintenance` with `ProtectedRoute` for access 
   control.

2.  feat: Implement navigation to the new maintenance creation page
- Added useNavigate hook for routing in MyComponent
- Created navigateToNewMaintenance function to handle routing to /maintenance/createnewmaintenance
- Updated button onClick to trigger navigation function

Please review my codes. Thank you!

## Summary by CodeRabbit

- **New Features**
  - Added a new route `/maintenance/create` for creating new maintenance records.
  - Introduced a `CreateNewMaintenance` component for the new route.

- **Style**
  - Updated font size to `13px` for maintenance checklist buttons.

- **Chores**
  - Enhanced navigation in the maintenance section with `useNavigate` integration.

### CODE REVIEW

**Review by danielcj2 — APPROVED** [review]
Seems good to merge. Personally, I would continue pushing changes to this branch until we have something more concrete to present for creating the maintenance window, but I will defer to my peers on this one.

Oh and one small change that would probably be good just for the sake of simplicity. I would go ahead and change the path name from `/maintenance/createnewmaintenance` to `/maintenance/create`. Aligns with our other routes, and much easier to read.

**Review by ajhollid — CHANGES_REQUESTED** [review]
Agreed with @danielcj2 , the route needs to be changed to match conventions.  Otherwise looks good to me :+1: 

I think you can change it to `/maintenance/create` for now, though we may want to change it in the future.

**Comment by terryjung0244** [comment]
Thanks for the comments.

I changed the path from /maintenance/createnewmaintenance to /maintenance/create.

**Comment by ajhollid** [comment]
@terryjung0244 will resubmit this branch when ready

**Pull request closed without merging**
