### PR TITLE
Maintenance window options screen

### PR DESCRIPTION
**Pull request by MuhammadKhalilzadeh**
Here's the implementation of maintenance window options screen. 
I tried different ways, but I could not find any ways to change the Date Picker and Time Picker appearance to match the our designs.

Screenshot 2024-07-26 145028

### CODE REVIEW

**Comment by MuhammadKhalilzadeh** [comment]
And also for these dropdowns, I targeted many classes, but disabling neither of them couldn't invisible this blue background-color!

Screenshot 2024-07-26 145544

**Comment by gorkem-bwl** [comment]
HH:MM picker: how does the user experience look like there? Is it possible for the user select hour, minute and AM/PM?

**Comment by MuhammadKhalilzadeh** [comment]
Yes, this is how it looks
Screenshot_20240726_161627_Chrome

**Comment by MuhammadKhalilzadeh** [comment]
@gorkem-bwl how do you like it?

**Comment by gorkem-bwl** [comment]
> @gorkem-bwl how do you like it?

Looks great to me!

**Comment by MuhammadKhalilzadeh** [comment]
@gorkem-bwl  Then let's go with this. 👍🏻
How about other parts?

**Comment by gorkem-bwl** [comment]
> @gorkem-bwl Then let's go with this. 👍🏻 How about other parts?

Can you dynamically search for other monitors at the “add monitors” section?

**Comment by MuhammadKhalilzadeh** [comment]
@gorkem-bwl I believe it's for the same exact purpose, but first we need to connect it to backend and bind it to the UI.
This issue (task) is just for creating the UI component of Maintenance window options screen.

**Comment by ajhollid** [comment]
> And also for these dropdowns, I targeted many classes, but disabling neither of them couldn't invisible this blue background-color!
> 
> Screenshot 2024-07-26 145544

@MuhammadKhalilzadeh we have a select component in the project now you should be able to just drop in here

**Comment by MuhammadKhalilzadeh** [comment]
I don't think so!
My branch is up-to-date and I'm not finding any select components other than this one I'm using.
Which folder is it? Is it added recently?

**Comment by MuhammadKhalilzadeh** [comment]
@ajhollid What's the name of the component we've created with it?

**Comment by ajhollid** [comment]
> @ajhollid What's the name of the component we've created with it?

It's under Inputs.

It appears some of the changes you've made here are targeting global classes which have broken some components though.

We'll have to dig through it and find out what's going on.

Try and keep those CSS selectors as specific as possible, if you target too broadly you'll affect other components

**Comment by MuhammadKhalilzadeh** [comment]
@ajhollid  Okay, then I guess we'll need to set a meeting and review and discuss my code in this part.

**Comment by ajhollid** [comment]
With additions and deletions this PR is close to 800 lines, our target for pull requests should be at a maximum 200 lines.

It's going to take a while to go through the whole thing, we may have to go component by component since there are a lot in this PR.

In future it would be best to have one PR per component, we can get code reviewed faster and feedback can be incorporated.

**Comment by MuhammadKhalilzadeh** [comment]
No! it's not that much. I know the exact components I've worked on.
We can review them easily

**Comment by ajhollid** [comment]
> No! it's not that much. I know the exact components I've worked on.
> We can review them easily



789 lines to go review here, you can see how many lines you have changed by running `git diff` before you commit. 

We have to be very careful in this review because we don't know what components have been affected by the wide CSS targets.

At the very least the Select component appears to have been broken by globally selecting the Input class.

**Comment by ajhollid** [comment]
> Let's me think what we can do and get back to you asap

Sent DM on discord, let's pick up the discussion there 🙏

**Comment by ajhollid** [comment]
> @gorkem-bwl I believe it's for the same exact purpose, but first we need to connect it to backend and bind it to the UI.
> This issue (task) is just for creating the UI component of Maintenance window options screen.

This shouldn't actually require a new backend request, all the monitors are in the redux store since they are fetched when the user first logs in.

You can just grab them from the redux store and build the autocomplete data from them 😎

**Pull request closed without merging**
