### PR TITLE
Feat/monitor to backend, resolves #160

### LINKED ISSUE #160: Front End - Connect Monitors page to Backend
Montiors page needs to be conected to the redux store.

`monitorSlice` defines the async requests to the backend as well as the state of the monitors, monitor state should be used to populate the page.

### PR DESCRIPTION
**Pull request by ajhollid**
This PR connects the monitor page to the backend and display actual data from monitors.

I apologize for the size of the PR, but there were quite a few interelated components that had to be updated together.

Please take your time to review.

I also included normalization for the data checks.  I believe this is probably best done on the backend to keep client performance as high as possible, so we can think about refactoring this in the next PR.

[Source for normalization functinon](https://en.wikipedia.org/wiki/Feature_scaling#Rescaling_(min-max_normalization)), please double check I've implemented this properly.

PR from the air! :airplane:

### CODE REVIEW

**Comment by danielcj2** [comment]
I've reviewed the code and couldn't find any issues. Everything looks good to me! Good stuff 🙌

**Comment by ajhollid** [comment]
> I like what you did. kudos!

Thank you for laying all the groundwork here :smile:

**Comment by gorkem-bwl** [comment]
In your presentation I saw two different charts. Are they from chartjs?

**Comment by ajhollid** [comment]
> In your presentation I saw two different charts. Are they from chartjs?

They are components @MuhammadKhalilzadeh made, he had some trouble intergrating ChartJS.  We're planning to eventually move to ChartJS once we get it sorted out

**Comment by gorkem-bwl** [comment]
> > In your presentation I saw two different charts. Are they from chartjs?
> 
> They are components @MuhammadKhalilzadeh made, he had some trouble intergrating ChartJS. We're planning to eventually move to ChartJS once we get it sorted out

OK, makes sense.

**Pull request merged**
