### PR TITLE
BE | Add biome to package scripts

### LINKED ISSUE #776: BE - Using linters and formatters
## Using linters and formatters on the server side

BlueWave Uptime frontend created with vite, so it has predefined linter and formatter scripts in the `package.json` file. For example it can terminate the build stage when there is a lint error or warning and this can help developer to understand that something goes wrong.

We can also add linting and formatting tools to server side, which will positively impact the developer experience.

### My Solution

Using [biome](https://biomejs.dev/). Biome is an integrated and fast development tool chain for linting and formatting like processes. It can be easily implemented.

```shell
# Detect the problems
biome lint . 

# Detect and fix the available problems
biome lint --write . 
```
### Alternative Solutions

Biome is not the only tool, there are many solutions.

- [eslint](https://eslint.org/)
- [prettier](https://prettier.io/)

#### Additional context

- [Biome Guides](https://biomejs.dev/guides/getting-started/)

### PR DESCRIPTION
**Pull request by mertssmnoglu**
Resolves #776 

- Using default formatter rules
- Using recommended linter rules
- :exclamation: New development dependency: `@biomejs/biome`

## Information

First run of the formatter will cause some conflicts with the current PRs because it will change all of the files. It can be a good practice to determine the code style as soon as you start. [Formatter Configuration Reference](https://biomejs.dev/reference/configuration/#formatter)

## Scripts

This scripts also be able to run with [node --run](https://nodejs.org/api/cli.html#--run) in next LTS release. I hope so.

### lint

Check the problems/warnings/errors

```shell
npm run lint
```

### lint:fix

Fix the problems/warnings/errors if they are fixable

```shell
npm run lint:fix
```

### format

Format the codebase with the given configuration in `biome.json`

```shell
npm run format
```

### format:check

Check the codebase for formatting issues

```shell
npm run format:check
```

### CODE REVIEW

**Comment by ajhollid** [comment]
Thanks for putting this together, I don't have the bandwidth at the moment to come up with all the linting rules we'd like for the backend, perhaps we can revisit this when we have more time available to consider the linitng rules.

**Comment by mertssmnoglu** [comment]
> Thanks for putting this together, I don't have the bandwidth at the moment to come up with all the linting rules we'd like for the backend, perhaps we can revisit this when we have more time available to consider the linting rules.

Hello, is there any idea or progress on this topic?

**Comment by gorkem-bwl** [comment]
> > Thanks for putting this together, I don't have the bandwidth at the moment to come up with all the linting rules we'd like for the backend, perhaps we can revisit this when we have more time available to consider the linting rules.
> 
> Hello, is there any idea or progress on this topic?

Is it possible to push this a little bit back, to open some room for agent-driven data collection? How about we start with this right after we build the agents and corresponding UI/backend?

**Comment by ajhollid** [comment]
We've decided to go with prettier for the time being as it is time tested and everyone on the team is familiar with it.  Thanks for your effort here though!

**Pull request closed without merging**
