### PR TITLE
Fix/theme toggle position - issue#934

### LINKED ISSUE #934: [Enhancement]: Light/Dark mode toggle should be in settings menu
The light/dark mode toggle is currently present at the user profile menu along with the log out button. Rather it should be in the settings menu under appearance.

Screenshot 2024-10-11 113132

### PR DESCRIPTION
**Pull request by rishavd3v**
## Description
Moved theme switch toggle to settings menu.

https://github.com/user-attachments/assets/0523cc44-fb8e-426c-b902-fd9aa29db66d

## Related Issue
Closes #934

### CODE REVIEW

**Review by ajhollid — APPROVED** [review]
Looks good to me, nice work!  Thank you for your contribution :+1:

**Comment by rishavd3v** [comment]
> Looks good to me, nice work! Thank you for your contribution 👍

Small request! If possible, can you please add `hacktoberfest-accepted` label to my PR ( #938 and #944 ) so that it can count towards my Hacktoberfest contributions?
I appreciate your help and the opportunity to contribute to this project!

**Comment by gorkem-bwl** [comment]
I just added hacktoberfest-accepted as a topic of the repo, so it should count towards your Hacktoberfest contributions. I believe that is the only requirement as per https://hacktoberfest.com/participation

**Comment by rishavd3v** [comment]
That's great! Thanks a lot @gorkem-bwl

**Pull request merged**
